name: breakaway365_web
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  intl: 0.20.2
  http: ^1.0.0
  cloud_firestore_web: any
  firebase_auth_web: any
  firebase_core_web: any
  firebase_storage_web: any
  url_launcher_web: any
  video_player_web: any
  flutter_web_plugins:
    sdk: flutter
  firebase_storage: any
  video_player: '>=2.9.2'
  url_launcher: ^6.3.0
  cloud_firestore: any
  firebase_auth: any
  firebase_core: ^4.3.0
  fl_chart: 0.68.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  pdf: ^3.0.0
  printing: ^5.0.0
  universal_html: ^2.0.0
  file_picker: '>=8.1.2'
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
